services:
  mysql:
    image: mysql:8.0
    container_name: msp-dev-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: msp
      MYSQL_USER: msp
      MYSQL_PASSWORD: msp123456
      MYSQL_ROOT_PASSWORD: root123456
    volumes:
      - msp-mysql-data:/var/lib/mysql
volumes:
  msp-mysql-data:
